Added new features and fixed bugs
tritondigital/android-sdk pull request #12
Opened 2024-04-23 10:24 UTC by Andre3567

2024-04-23 11:02 UTC, EddieGr requested changes

2024-04-23 11:02 UTC, EddieGr commented on player/src/main/java/com/tritondigital/player/StationPlayer.java
> +            AnalyticsTracker tracker = AnalyticsTracker.getTracker(getContext());
Check to remove Analytics Tracker in this file.

2024-04-23 11:02 UTC, EddieGr commented on player/src/main/java/com/tritondigital/player/StationPlayer.java
> +            AnalyticsTracker tracker = AnalyticsTracker.getTracker(getContext());
And everything related to it.

2024-04-23 11:02 UTC, EddieGr commented on player/src/main/java/com/tritondigital/player/StationPlayer.java
> +            AnalyticsTracker tracker = AnalyticsTracker.getTracker(getContext());
Remove whole section

2024-04-23 14:50 UTC, EddieGr approved these changes

2024-04-23 14:52 UTC, EddieGr requested changes
Check if you can get to a startup.

2024-04-25 06:52 UTC, jd-buys requested changes

2024-04-25 06:52 UTC, jd-buys commented on player/src/main/java/com/tritondigital/player/CuePointHistory.java
> +    private static final String SERVER_PREPROD = "https://example.preprod01.net";
Please remove the preprod environment stuff

2024-04-25 06:52 UTC, jd-buys commented on player/src/main/java/com/tritondigital/player/Provisioning.java
> +    private static final String DOMAIN_NAME_PROD = "exampleProdserver.com";
This is the wrong prod domain name. The playerservices.streamtheworld.com was correct.

2024-04-25 06:52 UTC, jd-buys commented on player/src/main/java/com/tritondigital/player/Provisioning.java
> +    private static final String SERVER_PREPROD   = "https://example.Preprod.server/api/livestream";
Remove the dev and preprod values

2024-04-25 06:52 UTC, jd-buys commented on player/src/main/java/com/tritondigital/player/Provisioning.java
> +                case ".preprod": serverUrl = SERVER_PREPROD; break;
Remove preprod and dev

2024-04-25 06:52 UTC, jd-buys commented on player/src/main/java/com/tritondigital/player/StationPlayer.java
> +    private static final String DOMAIN_NAME_PROD = "example.com";
The domain_name_prod has the wrong value.
Please remove preprod.

2024-04-25 06:52 UTC, jd-buys commented on player/src/main/java/com/tritondigital/player/StationPlayer.java
> +                    case "preprod": programUrl = String.format("https://%s/api/cloud-redirect/%s/stream-info", DOMAIN_NAME_PREPROD, mountArgs[0]); break;
Remove preprod

2024-04-25 09:12 UTC, EddieGr approved these changes

2024-04-25 09:53 UTC, merged